### ISSUE TITLE
BestInSlotRedux High CPU cost?

### ISSUE THREAD

**Issue by DoubleHighC** [anhility/BestInSlotRedux#40]
Hi there

I really like this addon and use it on all of my chars in wow but today I found an "maybe" issue!

I was in my orderhall just sending away my followers and doing some sort my bags stuff and then I opened addon usage to see my cpu load of the addons because I'm allways trying to find addons that are taking to much of cpu load for my tast and then switch them of for raiding or search for an alternative!

I know tradeskillmaster is a ton of load on memory and cpu when doing something in the bags or auctionhouse but BestInSlotRedux nealy took doubble of the cpu load and I was in no raid or anything else and did not do anything with it at all, so how comes that it take so much cpu load when I do not do anything with it or even would not even need it in that situation?

![screen1](https://user-images.githubusercontent.com/36462582/36184513-711c145c-1134-11e8-9910-c5115328b1d4.jpg)

Thank you in advance

**Comment by anhility** [comment]
Hello.
I've looked into it a little and have not been able to replicate it while just standing around in the order hall.
The CPU usage should otherwise be fairly low as for me it hovers around 0.3 ms/s.
A guess I have is that you might have managed to scan the CPU just as someone asked your addon to share your BiS lists and that made the addon work hard in the background.

I'll close this issue but if you notice it happening again and you can replicate it, please make another reply and I'll reopen the issue.
